# uploader une version récente de yarn pour utiliser yarn version --patch sans prompt
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

# permet d'utiliser les conditions basées sur le message du commit => if: commit_message  
conditions: v1

# ne pas lancer le job pour les commits message 'Travis CI'
if: commit_message !~ /(Travis CI|wip)/

sudo: false
git:
  depth: 1

matrix:
  fast_finish: true

cache: yarn

language: node_js
node_js:
  - "node"

# Seul le stage all est utilisé, le découpage par stage etait intéressant mais Travis recrée un nouvel espace de travail à chaque stage,
# et c'est pas cool...
jobs:
  include:
    - stage: all
      node_js: "lts/*"
      script: ./ci/all
    - stage: test
      node_js: "lts/*"
      script: ./ci/test
    - stage: build
      node_js: "lts/*"
      script: ./ci/build

# A modifier, ne faire que les tests pour les branches != master
stages:
  - name: all
    if: branch = master
  - name: test
    if: branch != master
  - name: build
    if: branch != master
