conditions: v1

if: commit_message !~ /(Publish|wip)/

sudo: false
git:
  depth: 1

matrix:
  fast_finish: true

cache: yarn

language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: all
      node_js: "lts/*"
      script: ./ci/bump

stages:
  - name: all
    if: branch = master
