before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

conditions: v1

if: commit_message !~ /(Travis CI|wip)/

sudo: false
git:
  depth: 1

matrix:
  fast_finish: true

cache: yarn

language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: all
      node_js: "lts/*"
      script: ./ci/all

stages:
  - name: all
    if: branch = master
