if: tag IS blank

sudo: false
git:
  depth: 1

matrix:
  fast_finish: true

cache: yarn

language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: bump
      node_js: "lts/*"
      script: ./ci/bump
    - stage: test
      node_js: "lts/*"
      script: ./ci/test
    - stage: build
      node_js: "lts/*"
      script: ./ci/build
    - stage: publish
      script: ./ci/publish
    - stage: tag
      script: ./ci/tag

stages:
  - name: bump
    if: branch = master
  - test
  - build
  - name: publish
    if: branch = master
  - name: tag
    if: branch = master
