#!/bin/sh

set -xe

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

setup_git
git checkout master

npx lerna publish --cd-version=patch --yes --skip-npm -m "Travis CI Publish %s"
yarn config set version-git-message "Travis CI Bump v%s"
yarn version --patch
git push "https://${GITHUB_TOKEN}@github.com/hjumeau/lerna-example.git" master

npx lerna bootstrap
npx lerna run test:ci

npx lerna run build

npx lerna publish --cd-version=patch --yes --skip-git

git push "https://${GITHUB_TOKEN}@github.com/hjumeau/lerna-example.git" --tags
