#!/bin/sh

set -xe

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

setup_git
git checkout master
npx lerna publish --cd-version=patch --yes --skip-npm
git push "https://${GITHUB_TOKEN}@github.com/hjumeau/lerna-example.git" master > /dev/null 2>&1
